version: '3'

services:
  app:
    image: nicopaez/password-api:latest
    restart: always
    
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app